# Generated by Django 4.2.30 on 2026-10-03 06:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.BigIntegerField(db_index=True, help_text="DevPerf's id for the organization this row belongs to.")),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Used in the public join URL instead of the numeric id, so a student cannot guess or enumerate other sessions.', unique=True)),
                ('name', models.CharField(max_length=150)),
                ('identify_by', models.CharField(choices=[('full_name', 'Full name'), ('student_id', 'Student ID')], default='full_name', help_text='Which roster field a student types in to join.', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('group_weight_percent', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5)),
                ('individual_weight_percent', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5)),
                ('voting_paused', models.BooleanField(default=False, help_text='Lecturer-controlled kill switch: no evaluation can be submitted while true, independent of which turn is active.')),
                ('joining_locked', models.BooleanField(default=False, help_text='Prevent additional students from joining after the room is ready.')),
                ('default_presentation_seconds', models.PositiveIntegerField(blank=True, help_text='Optional target presentation duration (seconds) shown as a countdown to the presenting group and on the public screen. Does not auto-advance the session — it is informational only, giving the lecturer a visible cue for when to open voting. Null means no presentation timer is set.', null=True)),
                ('default_turn_seconds', models.PositiveIntegerField(blank=True, help_text='Remembered voting-timer length (seconds) from the last time the lecturer activated a group — prefills the control next time rather than resetting it. Null means "no timer" was last chosen.', null=True)),
                ('transition_gap_seconds', models.PositiveIntegerField(default=0, help_text="Pause (seconds) between one group's voting closing and the next group automatically starting, so an auto-advancing session gives everyone a breather instead of snapping straight into the next group with zero delay. 0 means no gap — advance immediately, as before.")),
                ('pending_transition_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_sessions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PresentationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('max_size', models.PositiveIntegerField(blank=True, help_text='Optional cap on members (e.g. 2). Leave blank for no limit.', null=True)),
                ('assessment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='assessments.assessmentsession')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('student_id', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('programme', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='assessments.assessmentsession')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='RubricCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('scope', models.CharField(choices=[('group', 'Group / project'), ('individual', 'Individual student')], default='group', max_length=10)),
                ('max_points', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="This category's real share of the 100-point final score - group-scope weights sum to the session's group weight percent, individual-scope weights to its individual weight percent.", max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('assessment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_categories', to='assessments.assessmentsession')),
            ],
            options={
                'verbose_name_plural': 'rubric categories',
                'ordering': ['scope', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PresentationTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('closed', 'Closed')], default='pending', max_length=10)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('voting_opened_at', models.DateTimeField(blank=True, help_text='When voting actually started. If null on an active turn, the group is presenting but voting has not yet opened.', null=True)),
                ('voting_ends_at', models.DateTimeField(blank=True, help_text='When set, voting for this turn auto-closes at this time and the session automatically advances to the next group (assessments.turns.auto_advance, scheduled via Celery). Cleared while the session is paused — see paused_remaining_seconds — so a stale scheduled task that fires during the pause has nothing to act on.', null=True)),
                ('paused_remaining_seconds', models.PositiveIntegerField(blank=True, help_text='Time left on the countdown at the moment voting was paused, so resuming restores exactly that much time instead of the countdown having kept running unseen.', null=True)),
                ('presentation_ends_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_turns', to='assessments.assessmentsession')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='assessments.presentationgroup')),
            ],
            options={
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to='assessments.student')),
                ('presentation_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='assessments.presentationturn')),
                ('target_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to='assessments.student')),
            ],
            options={
                'unique_together': {('presentation_turn', 'evaluator', 'target_student')},
            },
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='designated_next_group',
            field=models.ForeignKey(blank=True, help_text='Lecturer-chosen next group in line. Takes precedence over default order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assessments.presentationgroup'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='pending_next_group',
            field=models.ForeignKey(blank=True, help_text='Set while a timed transition gap is counting down (see `transition_gap_seconds`) — the group that will become active once `pending_transition_at` arrives.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assessments.presentationgroup'),
        ),
        migrations.CreateModel(
            name='ParticipationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('assessment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_records', to='assessments.assessmentsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_records', to='assessments.student')),
            ],
            options={
                'unique_together': {('assessment_session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='assessments.presentationgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='assessments.student')),
            ],
            options={
                'unique_together': {('group', 'student')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessments.evaluation')),
                ('rubric_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessments.rubriccategory')),
            ],
            options={
                'unique_together': {('evaluation', 'rubric_category')},
            },
        ),
    ]
