# Generated by Django 4.2.30 on 2026-10-05 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0002_sessiontransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationgroup',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='presentationgroup',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='SessionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='assessments.assessmentsession')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
